# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket      = "terragrunt-terraform-remote-state"
    credentials = "/Users/michael/.config/gcloud/central-beach-194106-9def8e1a069f.json"
    prefix      = "openshift/us-central1/usc1-demo/terraform.tfstate"
  }
}
