#!/bin/bash

apt update -y
apt upgrade -y

apt install -y wget curl gnupg2 software-properties-common awscli jq

# Configure AWS credentials if provided
%{ if aws_access_key_id != null && aws_secret_access_key != null }
mkdir -p /root/.aws
cat > /root/.aws/credentials <<EOL
[default]
aws_access_key_id = ${aws_access_key_id}
aws_secret_access_key = ${aws_secret_access_key}
aws_session_token = ${aws_session_token}
EOL

cat > /root/.aws/config <<EOL
[default]
region = ${aws_region}
EOL
%{ endif }

echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf
echo 'net.core.somaxconn = 1024' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

echo 'never' | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' | sudo tee /sys/kernel/mm/transparent_hugepage/defrag

sudo tee -a /etc/rc.local <<EOL
#!/bin/bash
echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
exit 0
EOL
sudo chmod +x /etc/rc.local

sleep 30

sudo systemctl stop ufw
sudo systemctl disable ufw

mkdir /tmp/redis
cd /tmp/redis || exit

echo "Installing Redis Enterprise"

echo "Disabling DNS stub listener"
cat > /etc/systemd/resolved.conf << EOF
[Resolve]
DNS=${dns_server}
DNSStubListener=no
EOF

systemctl restart systemd-resolved

rm -f /etc/resolv.conf

cat > /etc/resolv.conf << EOF
# Custom DNS configuration
# Generated by Redis install script
nameserver ${dns_server}
EOF

chattr +i /etc/resolv.conf

echo "Copying installation tar file"
aws s3 cp s3://redis-enterprise-software/${redis_distribution} ./redis-enterprise.tar

tar -xf redis-enterprise.tar

if [ -f "install.sh" ]; then
    echo "Running installation script"
    ./install.sh -y
else
    echo "No recognized installation method found"
    exit 1
fi

cd /
rm -rf /tmp/redis

CURRENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
echo "Current node IP: $CURRENT_IP"
echo "$CURRENT_IP $(hostname)" | sudo tee -a /etc/hosts
