#!/bin/bash

apt update -y
apt upgrade -y

apt install -y wget curl gnupg2 software-properties-common awscli jq

cat > /root/.aws/config <<EOL
[default]
region = ${aws_region}
EOL

echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf
echo 'net.core.somaxconn = 1024' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p

echo 'never' | sudo tee /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' | sudo tee /sys/kernel/mm/transparent_hugepage/defrag

sudo tee -a /etc/rc.local <<EOL
#!/bin/bash
echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
echo 'never' > /sys/kernel/mm/transparent_hugepage/defrag
exit 0
EOL
sudo chmod +x /etc/rc.local

sleep 30

sudo systemctl stop ufw
sudo systemctl disable ufw

CURRENT_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
echo "Current node IP: $CURRENT_IP"
echo "$CURRENT_IP $(hostname)" | sudo tee -a /etc/hosts

echo "Disabling DNS stub listener"
cat > /etc/systemd/resolved.conf << EOF
[Resolve]
DNS=${dns_server}
DNSStubListener=no
EOF

systemctl restart systemd-resolved

rm -f /etc/resolv.conf

cat > /etc/resolv.conf << EOF
# Custom DNS configuration
# Generated by Redis install script
nameserver ${dns_server}
EOF

chattr +i /etc/resolv.conf

echo "Copying installation tar file"
aws s3 cp s3://redis-enterprise-software/rdi-installation-${rdi_version}.tar.gz /home/ubuntu/rdi.tar.gz

cd /home/ubuntu || exit
tar -xzf rdi.tar.gz
rm rdi.tar.gz
chown -R ubuntu:ubuntu rdi_install
