name: Auto Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

concurrency:
  group: auto-release-main
  cancel-in-progress: false

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (fetch all history & tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine next tag (patch bump)
        id: bump
        shell: bash
        run: |
          latest=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n1)
          if [[ -z "$latest" ]]; then
            next="v1.0.0"
          else
            base="${latest#v}"
            IFS='.' read -r major minor patch <<< "$base"
            patch=$((patch + 1))
            next="v${major}.${minor}.${patch}"
          fi
          echo "latest_tag=${latest}" >> "$GITHUB_OUTPUT"
          echo "next_tag=${next}" >> "$GITHUB_OUTPUT"
          echo "Next tag: ${next}"

      - name: Create release (auto-adds source zip/tar.gz)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.bump.outputs.next_tag }}" \
            --target "${GITHUB_SHA}" \
            --generate-notes \
            --title "Release ${{ steps.bump.outputs.next_tag }}"
